### ISSUE TITLE
Unable to pipe output of minigun cli

### ISSUE THREAD

**Issue by tomgco** [shoreditch-ops/minigun#33]
```
tomg@ttlpenguin ~/ (minigun●●)(4.2.4)$ DEBUG=rascal:Publication minigun run -e local test/load/searches.json | grep 'Publishing 215' | uniq -c
/usr/local/lib/node_modules/minigun/node_modules/cli/cli.js:1147
        stream.clearLine();
               ^

TypeError: stream.clearLine is not a function
    at null._repeat (/usr/local/lib/node_modules/minigun/node_modules/cli/cli.js:1147:16)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by hassy** [comment]
Thanks :+1:
